name: hello world

on:
  push:
    branches:
       - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: all_in_docker/client

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: executing remote ssh commands using passwordss
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            whoami
  

